sudo: false

language: node_js
node_js: "11.6.0"

# before_install:
#   - npm install

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - GH_TOKEN=0c2ead6a2dc0da2f298be9040a66fa2a2da3cae2

jobs:
  include:
    - stage: Deploy Windows
      os: windows
      script:
        - npm install electron-builder@20.28.4 -g && npm run release
    - stage: Deploy Windows & Mac
      if: tag IS present
      os: osx
      osx_image: xcode10.1
      script:
        - npm run release -- --mac --win
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine
    - stage: Deploy linux
      if: tag IS present
      os: linux
      dist: trusty
      script:
        - npm run release
