language: node_js
node_js: "9.11.1"

before_install:
  - npm install app-builder-bin

cache:
  directories:
    - node_modules
    - app/node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

jobs:
  include:
    - stage: Deploy Linux
      os: linux
      dist: trusty
      script:
        - npm run release
    - stage: Deploy Mac
      os: osx
      osx_image: xcode10.1
      script:
        - npm run release
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine
    - stage: Deploy Windows
      os: windows
      script:
        - npm run release
